import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: {
    template: '& | moms',
    absolute: 'moms',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mx-auto bg-yellow-50`}>
        <div
          style={{
            backgroundImage: "url('/배경.png')",
            backgroundSize: 'cover',
            backgroundPosition: 'center',
            minHeight: '100vh',
            opacity: 0.5, // 배경 투명도 50% 설정
            position: 'fixed', // 배경 이미지 고정
            top: 0,
            left: 0,
            right: 0,
            bottom: 0,
            zIndex: -1,
            backgroundRepeat: 'repeat', // 이미지 반복
          }}
        />
        {children}
      </body>
    </html>
  );
}
